### DISCUSSION TITLE
multiple choice tabular question - doesn't display correctly on smaller screen

### DISCUSSION THREAD

**Discussion by MalikaIhle** [rubenarslan/formr.org#574] [Q&A] [answered]
I have created several questions in a tabular format (for one question, several items are rated on the same scale), using mc_heading.
However, if I resize the window to something less wide, the display become such that we do not know which tick box belong to which heading. 
In the case of multiple options - single choice question, at some point (around the phone size display), the format makes sense again as the scale is repeated for each item. However, for questions with multiple choices, multiple andswers possible, the scale completely disappear and the tick boxes don't have any labels anymore. 

See examples screen shoted below:

1. Single choice:  
a. laptop display  

<img width="561" alt="Q4_correct_display" src="https://github.com/user-attachments/assets/b973af2a-013b-4642-a433-cf5858a6db95">

b. half a laptop screen --> **problematic**  

<img width="375" alt="Q4_wrong_display" src="https://github.com/user-attachments/assets/7d604dec-7ac6-44b5-a33d-a659b154f0a1">

c. phone size display  

<img width="342" alt="Q4_appropriate_display_if_resized" src="https://github.com/user-attachments/assets/5fc1f3c9-8cef-4db5-82fc-36f06a4e4ff4">

2. multiple choice:  
a. laptop display  

<img width="575" alt="Q6_correct_display" src="https://github.com/user-attachments/assets/c5119916-f3f1-4ea1-a9e2-5386c7c6fc22">

b. half a laptop screen --> **problematic**  

<img width="366" alt="Q6_wrong_display" src="https://github.com/user-attachments/assets/dea79f1d-a207-4789-8b4b-5062bf584d0e">

c. phone size display --> **extremely problematic**  

<img width="272" alt="Q6_scale_disappeared" src="https://github.com/user-attachments/assets/ccd74bc0-340e-48c0-a9d7-a5d96f9bf399">

Any advice?
Thanks and best wishes
Malika 
malika.ihle@lmu.de

**Comment by rubenarslan** [comment]
Hi Malika, can you attach an xls file of your survey with which I can reproduce the problem?

I generally don't recommend this kind of design. I think many still use it because paper surveys look like this (to save paper). But I think it's cognitively taxing and harder to click on and on the screen we don't have to be economical with space.

**Comment by MalikaIhle** [comment]
[group_onboarding_survey.xlsx](https://github.com/user-attachments/files/17279589/group_onboarding_survey.xlsx)

Thanks for the prompt reply! I think the whole team prefers this design, altough the phone version could work too I suppose.

**Comment by rubenarslan** [comment]
You can copy this to your run -> settings -> CSS and fiddle with the max-width value to get your desired breakpoint.


```css
@media (max-width: 1000px) {
	/* display mc_heading style displays on mobile, when question and choices stack, aren't side-by-side */
	form.form-horizontal div.form-row.item-mc_heading.form-group {
		display: none;
	}
	form.form-horizontal div.form-row.form-group.hide_label div.controls label {
		text-align: inherit;
		text-indent: inherit;
		height: inherit;
		overflow: inherit;
		line-height: inherit;
		min-height: inherit;
	}
	form.form-horizontal div.form-row.form-group.hide_label div.controls label span, form.form-horizontal div.form-row.form-group.hide_label div.controls label span.mc-span {
		line-height: inherit;
		visibility: visible;
		display: inline-block;
	}
	form.form-horizontal div.form-row.form-group.hide_label div.controls label input {
		visibility: visible;
	}
	/* make check buttons vertical */
	form.form-horizontal div.form-row.form-group:not(.mc_horizontal) div.controls label:not(.keep-label), form.form-horizontal div.form-row.form-group:not(.mc_horizontal) div.controls button.btn {
		width: 100%;
	}
	form.form-horizontal div.form-row.form-group:not(.mc_horizontal) div.controls label:not(.keep-label) {
		margin-bottom: 10px;
		margin-left: 0px;
	}

}
```

**Comment by MalikaIhle** [comment]
Thanks! This works well for the  multiple choice - single option questions
![image](https://github.com/user-attachments/assets/b14ab751-5ec9-40b9-bbba-1ae59e1e1bae)
however, it doesn't for the multiple choice - multiple options questions:
![image](https://github.com/user-attachments/assets/d678a811-75f1-4f6d-8722-d0a275e5710d)
any ways to make the labels appear there too?

**Reply by rubenarslan** [reply, marked as answer]
Hi, here's a revised CSS snippet


```css

@media (max-width: 1200px) {
	/* display mc_heading style displays on mobile, when question and choices stack, aren't side-by-side */
	form.form-horizontal div.form-row.item-mc_heading.form-group {
		display: none;
	}
	form.form-horizontal div.form-row.form-group.hide_label div.controls label {
		text-align: left;
		text-indent: inherit;
		height: inherit;
		overflow: inherit;
		line-height: inherit;
		min-height: inherit;
	}
	form.form-horizontal div.form-row.form-group.hide_label div.controls label span, form.form-horizontal div.form-row.form-group.hide_label div.controls label span.mc-span {
		line-height: 25px !important;
		visibility: visible !important;
		display: inline-block  !important;
	}
	form.form-horizontal div.form-row.form-group.hide_label div.controls label {
	    text-align: left !important;
	}
	
	form.form-horizontal div.form-row.form-group.hide_label div.controls label span.cb-inline-label {
		line-height: 25px !important;
		visibility: visible !important;
		display: inline-block !important;
	}
	form.form-horizontal div.form-row.form-group.hide_label div.controls label input {
		visibility: visible;
	}
	/* make check buttons vertical */
	form.form-horizontal div.form-row.form-group:not(.mc_horizontal) div.controls label:not(.keep-label), form.form-horizontal div.form-row.form-group:not(.mc_horizontal) div.controls button.btn {
		width: 100%;
	}
	form.form-horizontal div.form-row.form-group:not(.mc_horizontal) div.controls label:not(.keep-label) {
		margin-bottom: 10px;
		margin-left: 0px;
	}

}
```
