### DISCUSSION TITLE
CSS customization for specific items -- Item ID needed?

### DISCUSSION THREAD

**Discussion by richrau** [rubenarslan/formr.org#609] [Q&A] [answered]
Years ago, I've customized an item's appearence in the run settings. Now, I've setup an identical run on another formr istance but the customization fails. Perhaps the item IDs used in the CSS code are not correct any longer? If so, where can I find the correct item IDs? For instance, part of my CSS code looks like:

#item19496446_1{
    display: none !important ;
}

**Comment by rubenarslan** [comment]
Hi @richrau yes the item ID will change when you recreate the study. A portable solution would be to assign a class to the item in the class column of the item sheet (e.g. "myhiddenclass") and change your CSS as follows. This specific class already exists though, so you should be able to just add the class "hidden" and the item should be hidden from view even without custom CSS.

```css
.myhiddenclass {
display: none !important ;
}
```

**Reply by richrau** [reply]
Thanks, but i think i need a different solution. My code is a hand-crafted workaround (not my own) to produce a horizontal likert scale with a left-aligned anchor on the one end and a right-aligned anchor on the other by hiding the left-most response option. So I guess a class that affects the full item instead of just the first response option is not what I want, right? Probably it's easier to just lookup the new item id and replace it in the existing code?

![grafik](https://github.com/user-attachments/assets/69aad8a1-2767-4235-930a-e10c9fc36a39)



/*Item anchors & Anzeige auf kleinen Bildschirmen Politische Einstellung*/
[for="item19496446_1"]{
    pointer-events: none;
}

[for="item19496446_1"] .circle{
    display: none !important ;
}

[for="item19496446_1"] .check{
    display: none !important ;
}

#item19496446_1{
    display: none !important ;
}
@media (max-width: 765px) {
    [for="item19496446_1"] .mc-span{
       transform: translateY(20px);
    }
}

**Reply by rubenarslan** [reply]
Ah, with the more complex query, I see the problem youre solving. Yes, you can just swap out the ID, or you can copy paste the CSS and HTML for the element into an LLM and ask it for a portable solution using :first-child. Or send a reproducible snippet to me, shouldnt be difficult.

**Reply by richrau** [reply]
I'd just like to go with the ID swap but I need your help in finding out the new ID that has been assigned. Where are these IDs listed?

**Reply by rubenarslan** [reply]
You have to create the form, test it and inspect the HTML of the input element Im afraid. its not meant to be a user facing feature.

**Reply by richrau** [reply]
got it, thanks!

**Reply by richrau** [reply]
Okay, I'm realizing it affects many more items than I originally thought, so inspecting all the HTMLs is too troublesome. Can I come back to your offer to send reproducible snippet? Here's the spreadsheet: https://docs.google.com/spreadsheets/d/12BZAaHLccn-1tYJf_udZtd_IkJCOepKHJjvvYUeRJbw/edit?gid=0#gid=0 (you can focus on the politics3 item on the first survey page). For the CSS code, see my comment above.

**Reply by rubenarslan** [reply]
Can't you just use type `rating_button 1,7` to achieve the desired look? Or do you want the radio buttons?

**Reply by rubenarslan** [reply, marked as answer]
Anyway, here is a CSS snippet that works in my test. Currently, it targets the `answer_below_label` because you use it already but you can also replace `.answer_below_label` with `.myspecialradiolayout` as long as you add that class in the survey item sheet.

```css
.answer_below_label label.radio-inline:first-of-type input[type="radio"] {
pointer-events: none;
}

.answer_below_label label.radio-inline:first-of-type input[type="radio"]
 .circle{
display: none !important ;
}

.answer_below_label label.radio-inline:first-of-type input[type="radio"]  .check{
display: none !important ;
}

.answer_below_label label.radio-inline:first-of-type input[type="radio"] {
display: none !important ;
}
@media (max-width: 765px) {
.answer_below_label label.radio-inline:first-of-type .mc-span {
        transform: translateY(2.5em);
        display: inline-block;
}
}
```
