### ISSUE TITLE
ESM styles by Kai

### ISSUE THREAD

**Issue by rubenarslan** [rubenarslan/formr.org#284]
@kthorstmann styles for phones have to be integrated at some point

```css
form.form-horizontal div.form-group.item-rating_button div.controls .controls-inner label.keep-label:first-of-type {
  min-width: 227px;
}

@media screen and (max-width: 768px) {

  /* Eingabe Panel auf volle Breite */
  form.form-horizontal div.form-group.item-rating_button div.controls .controls-inner {
    float: none;
    position: relative;
    width: 100%;
  }

  /* Setzt die beiden Elemente bei mobiler Ansicht fest nach oben links und oben rechts*/
  form.form-horizontal div.form-group.item-rating_button div.controls .controls-inner label.keep-label {
    position: absolute;
    /* min-width: 220px;   neu */
  }
  /* erstes label nach oben links */
  form.form-horizontal div.form-group.item-rating_button div.controls .controls-inner label.keep-label:first-of-type {
    /* v2: ein text align rechts bzw. links für das entsprechende label */
    text-align: left;
    left: 0;
    top: 0;
    /* gelöscht: min-width: auto;  */
  }
  /* letztes/zweites label nach oben rechts */
  form.form-horizontal div.form-group.item-rating_button div.controls .controls-inner label.keep-label:last-of-type {
    /* v2: ein text align rechts bzw. links für das entsprechende label */
    text-align: right;
    right: 0;
    top: 0;
  }

  /* Button Gruppe auf volle Breite */
  form.form-horizontal div.form-row.form-group.item-rating_button .btn-group {
    /* v2: buttons bekommen einen abstand nach oben, damit sie nicht über den labeln sind */
    margin-top: 25px;
    width: 100%;
  }
  /* jeder einzelne Button linksbündig und in 1/8 der Gesamtbreite */
  form.form-horizontal div.form-row.form-group div.controls button.btn {
    float: left;
    /* 1/8 Elemente */
    width: 12.5%;
  }
  /* jeder einzelne Button linksbündig und in 1/8 der Gesamtbreite */
  form.form-horizontal div.form-row.form-group div.controls button.btn.geolocator {
    float: left;
    /* 1/8 Elemente */
    width: 100%;
  }
  /* Rahmenrundungen des ersten und letzten Element raus */
  div.form-row.form-group .btn-group>.btn:first-child:not(:last-child) {
    border-radius: 0;
  }
  div.form-row.form-group .btn-group>.btn:last-child:not(:first-child) {
    border-radius: 0;
  }

  /* Ansonsten ist das erste und die restlichen Buttons nicht auf einer Linie*/
  div.form-row.form-group .btn-group>.btn+.btn {
    margin: 0;
  }
}

/* v2: button abstand und font-size der label kleiner für kleine mobiltelefone */
@media screen and (max-width: 375px) {
  form.form-horizontal div.form-group.item-rating_button div.controls .controls-inner label.keep-label {
    font-size: .775em; /* original .875em*/
  }

  form.form-horizontal div.form-row.form-group.item-rating_button .btn-group {
    margin-top: 20px; /* original 20 */
  }
}
```
