### ISSUE TITLE
enable iframe scrolling on iOS

### ISSUE THREAD

**Issue by rubenarslan** [rubenarslan/formr.org#343]
```css
.rmarkdown_iframe {
    overflow: auto;
    -webkit-overflow-scrolling: touch; /*MAKES OVERFLOWN OBJECTS HAVE INERTIA SCROLLING*/
}
```

should work
