### ISSUE TITLE
hide_label broken

### ISSUE THREAD

**Issue by rubenarslan** [rubenarslan/formr.org#453]
I guess you changed the class of the inline label span for mc_multiple items? This code repairs the hide_label class.

```css
form.form-horizontal div.form-row.form-group.hide_label div.controls label span.mc-span, form.form-horizontal div.form-row.form-group.hide_label div.controls label span.cb-inline-label {
	line-height: 0;
	visibility: hidden;
	display: none;
}
```
